# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='id',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.BaseModel')),
                ('doctor', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='medical.Patient')),
            ],
            bases=('medical.basemodel',),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.BaseModel')),
                ('details', models.CharField(max_length=500)),
            ],
            bases=('medical.basemodel',),
        ),
        migrations.CreateModel(
            name='ViewRequest',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.BaseModel')),
                ('allowed', models.BooleanField(default=False)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.AbstractBusinessUser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Patient')),
            ],
            bases=('medical.basemodel',),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.BaseModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Prescription'),
        ),
    ]
