# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentalAnalysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('score', models.FloatField()),
                ('magnitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField()),
                ('twitter_handle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sentimentalanalysisdata',
            name='twitter_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TwitterEntity'),
        ),
    ]
