# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentalanalysisdata',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
