# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sentimentalanalysisdata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterentity',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
