# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171013_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentalanalysisdata',
            name='tweet_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
