# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sentimentalanalysisdata_tweet_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentalanalysisdata',
            name='magnitude_normalized',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
